version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-node

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Vue build
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              npm run build:staging
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build:prod
            fi

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Copy files to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 cp dist s3://haohaotiantian.com --grant read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive
              aws cloudfront create-invalidation --distribution-id EZXGJW5MPGC3K --paths /index.html /app.js
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              aws s3 cp dist s3://staging.haohaotiantian.com --grant read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive
              aws cloudfront create-invalidation --distribution-id E14R2YU4CYXBZG --paths /index.html app.js
            fi