version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-node

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Vue build
          command: npm run build

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Copy files to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 cp dist s3://haohaotiantian.com --grant read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              aws s3 cp dist s3://staging.haohaotiantian.com --grant read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive
            fi